### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [d1y/github-to-cdn#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by d1y** [comment]
> If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

Okay, if you can, help submit a pr to improve ts support

(I don't quite understand how to write `d.ts`)

**Comment by geopic** [comment]
No worries, I'll have one done very shortly. Thank you for accepting.
